package provider

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/benjamin-lykins/terraform-provider-exedev/internal/client"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure vmResource satisfies the resource.Resource and
// resource.ResourceWithImportState interfaces.
var (
	_ resource.Resource                = &vmResource{}
	_ resource.ResourceWithImportState = &vmResource{}
)

// vmResourceModel maps the schema attributes for exedev_vm.
type vmResourceModel struct {
	// ID is the VM name (used as stable identifier in state).
	ID types.String `tfsdk:"id"`
	// Name is the VM name. Optional; exe.dev auto-generates one if omitted.
	Name types.String `tfsdk:"name"`
	// Image is the container image (e.g. "ubuntu:22.04").
	Image types.String `tfsdk:"image"`
	// Disk is the disk size at creation (e.g. "20GB"). Can be grown with resize.
	Disk types.String `tfsdk:"disk"`
	// Command overrides the default container start command.
	Command types.String `tfsdk:"command"`
	// Env is a map of KEY=VALUE environment variables.
	Env types.Map `tfsdk:"env"`
	// Integrations is a list of integration names to attach.
	Integrations types.List `tfsdk:"integrations"`
	// SetupScript is a script to run on first boot.
	SetupScript types.String `tfsdk:"setup_script"`
	// Hostname is the computed public hostname (name.exe.xyz).
	Hostname types.String `tfsdk:"hostname"`
	// Status is the computed VM status (running, stopped, etc.).
	Status types.String `tfsdk:"status"`
	// Region is the computed region where the VM was placed.
	Region types.String `tfsdk:"region"`
}

// vmAPIResponse is used to decode the JSON returned by exe.dev commands.
// Fields match the actual JSON keys returned by the ls --json command.
type vmAPIResponse struct {
	// ls --json returns vm_name; new --json may return name
	VMName   string `json:"vm_name"`
	Name     string `json:"name"`
	HTTPSURL string `json:"https_url"`
	Image    string `json:"image"`
	// disk_capacity_bytes is returned as an integer number of bytes
	DiskCapacityBytes int64  `json:"disk_capacity_bytes"`
	Status            string `json:"status"`
	Region            string `json:"region"`
	SSHDest           string `json:"ssh_dest"`
}

// effectiveName returns the VM name from whichever field is populated.
func (v vmAPIResponse) effectiveName() string {
	if v.VMName != "" {
		return v.VMName
	}
	return v.Name
}

// effectiveHostname returns the public hostname from the API response.
func (v vmAPIResponse) effectiveHostname() string {
	if v.HTTPSURL != "" {
		// strip the scheme to get just the hostname
		h := v.HTTPSURL
		if len(h) > 8 && h[:8] == "https://" {
			h = h[8:]
		}
		return h
	}
	if v.SSHDest != "" {
		return v.SSHDest
	}
	return v.effectiveName() + ".exe.xyz"
}

// vmListResponse is the envelope returned by ls --json.
type vmListResponse struct {
	VMs []vmAPIResponse `json:"vms"`
}

// vmResource is the concrete resource implementation.
type vmResource struct {
	client *client.Client
}

// NewVMResource returns a new vmResource factory function.
func NewVMResource() resource.Resource {
	return &vmResource{}
}

func (r *vmResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vm"
}

func (r *vmResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an [exe.dev](https://exe.dev) virtual machine.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The VM name, used as the stable identifier.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "VM name. Auto-generated by exe.dev if not specified.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"image": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Container image (e.g. `ubuntu:22.04`). Changing this forces a new VM.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"disk": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Disk size (e.g. `20GB`, `50G`). Can be increased after creation but never decreased.",
			},
			"command": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Container start command: `auto`, `none`, or a custom command. Changing this forces a new VM.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"env": schema.MapAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "Environment variables as a map of KEY to VALUE. Changing this forces a new VM.",
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.RequiresReplace(),
				},
			},
			"integrations": schema.ListAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "List of integration names to attach to the VM. Changing this forces a new VM.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
			},
			"setup_script": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Setup script to run on first boot (max 10 KiB). Changing this forces a new VM.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"hostname": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The public hostname of the VM (e.g. `my-vm.exe.xyz`).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Current VM status.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"region": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Region where the VM is running.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *vmResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data type",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = c
}

func (r *vmResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan vmResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	cmd, err := buildNewCommand(plan)
	if err != nil {
		resp.Diagnostics.AddError("Building new command", err.Error())
		return
	}

	tflog.Debug(ctx, "Executing exe.dev new command", map[string]any{"cmd": cmd})

	body, err := r.client.Exec(cmd)
	if err != nil {
		resp.Diagnostics.AddError("Creating VM", err.Error())
		return
	}

	vms, err := parseVMList(trimBOM(body))
	if err != nil || len(vms) == 0 {
		resp.Diagnostics.AddError("Parsing VM create response", fmt.Sprintf("could not parse response\nBody: %s", body))
		return
	}
	vm := vms[0]

	if vm.effectiveName() == "" {
		resp.Diagnostics.AddError("Parsing VM create response", "VM name not found in response: "+string(body))
		return
	}

	applyVMResponse(&plan, vm)

	// Do a Read to populate any fields the `new` response omits (status, region, etc.).
	if full, found, readErr := r.readVM(ctx, vm.effectiveName()); readErr == nil && found {
		applyVMResponse(&plan, full)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vmResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state vmResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vmName := state.ID.ValueString()
	vm, found, err := r.readVM(ctx, vmName)
	if err != nil {
		resp.Diagnostics.AddError("Reading VM", err.Error())
		return
	}
	if !found {
		// VM was deleted outside Terraform
		resp.State.RemoveResource(ctx)
		return
	}

	applyVMResponse(&state, vm)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *vmResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state vmResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	currentName := state.ID.ValueString()

	// Handle name change via rename.
	newName := plan.Name.ValueString()
	if newName != "" && newName != currentName {
		cmd := fmt.Sprintf("rename %s %s", client.ShellQuote(currentName), client.ShellQuote(newName))
		tflog.Debug(ctx, "Renaming VM", map[string]any{"cmd": cmd})
		if _, err := r.client.Exec(cmd); err != nil {
			resp.Diagnostics.AddError("Renaming VM", err.Error())
			return
		}
		currentName = newName
		plan.ID = types.StringValue(currentName)
	}

	// Handle disk resize.
	planDisk := plan.Disk.ValueString()
	stateDisk := state.Disk.ValueString()
	if planDisk != "" && planDisk != stateDisk {
		cmd := fmt.Sprintf("resize %s --disk=%s", client.ShellQuote(currentName), client.ShellQuote(planDisk))
		tflog.Debug(ctx, "Resizing VM disk", map[string]any{"cmd": cmd})
		if _, err := r.client.Exec(cmd); err != nil {
			resp.Diagnostics.AddError("Resizing VM disk", err.Error())
			return
		}
	}

	// Refresh state from the API.
	vm, found, err := r.readVM(ctx, currentName)
	if err != nil {
		resp.Diagnostics.AddError("Reading VM after update", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}

	applyVMResponse(&plan, vm)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *vmResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state vmResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vmName := state.ID.ValueString()
	cmd := fmt.Sprintf("rm %s", client.ShellQuote(vmName))
	tflog.Debug(ctx, "Deleting VM", map[string]any{"cmd": cmd})

	if _, err := r.client.Exec(cmd); err != nil {
		var execErr *client.ExecError
		// Treat 422 (command failed / already gone) as success for idempotency.
		if errors.As(err, &execErr) && execErr.StatusCode == 422 {
			return
		}
		resp.Diagnostics.AddError("Deleting VM", err.Error())
	}
}

func (r *vmResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// readVM fetches a single VM by name using `ls --l --json`.
// It returns (vm, true, nil) if found, (zero, false, nil) if not found,
// or (zero, false, err) on API error.
func (r *vmResource) readVM(ctx context.Context, name string) (vmAPIResponse, bool, error) {
	cmd := "ls --json"
	tflog.Debug(ctx, "Reading VM", map[string]any{"cmd": cmd})

	body, err := r.client.Exec(cmd)
	if err != nil {
		var execErr *client.ExecError
		if errors.As(err, &execErr) && (execErr.StatusCode == 404 || execErr.StatusCode == 422) {
			return vmAPIResponse{}, false, nil
		}
		return vmAPIResponse{}, false, err
	}

	body = trimBOM(body)

	vms, err := parseVMList(body)
	if err != nil {
		return vmAPIResponse{}, false, fmt.Errorf("parsing ls response: %w", err)
	}

	for _, vm := range vms {
		if vm.effectiveName() == name {
			return vm, true, nil
		}
	}
	return vmAPIResponse{}, false, nil
}

// parseVMList parses the various shapes the ls --json response may take.
func parseVMList(body []byte) ([]vmAPIResponse, error) {
	// Primary shape: {"vms": [...]}
	var envelope vmListResponse
	if err := json.Unmarshal(body, &envelope); err == nil && envelope.VMs != nil {
		return envelope.VMs, nil
	}
	// Fallback: flat array
	var list []vmAPIResponse
	if err := json.Unmarshal(body, &list); err == nil {
		return list, nil
	}
	// Fallback: single object
	var single vmAPIResponse
	if err := json.Unmarshal(body, &single); err == nil && single.effectiveName() != "" {
		return []vmAPIResponse{single}, nil
	}
	return nil, fmt.Errorf("unrecognised response shape: %s", body)
}

// buildNewCommand constructs the `new` CLI command string from the plan.
func buildNewCommand(plan vmResourceModel) (string, error) {
	var sb strings.Builder
	sb.WriteString("new --json")

	if !plan.Name.IsNull() && !plan.Name.IsUnknown() && plan.Name.ValueString() != "" {
		sb.WriteString(" --name=" + client.ShellQuote(plan.Name.ValueString()))
	}
	if !plan.Image.IsNull() && !plan.Image.IsUnknown() && plan.Image.ValueString() != "" {
		sb.WriteString(" --image=" + client.ShellQuote(plan.Image.ValueString()))
	}
	if !plan.Disk.IsNull() && !plan.Disk.IsUnknown() && plan.Disk.ValueString() != "" {
		sb.WriteString(" --disk=" + client.ShellQuote(plan.Disk.ValueString()))
	}
	if !plan.Command.IsNull() && !plan.Command.IsUnknown() && plan.Command.ValueString() != "" {
		sb.WriteString(" --command=" + client.ShellQuote(plan.Command.ValueString()))
	}
	if !plan.SetupScript.IsNull() && !plan.SetupScript.IsUnknown() && plan.SetupScript.ValueString() != "" {
		// Escape newlines as \n per the API docs.
		escaped := strings.ReplaceAll(plan.SetupScript.ValueString(), "\n", `\n`)
		sb.WriteString(" --setup-script=" + client.ShellQuote(escaped))
	}

	// Environment variables.
	if !plan.Env.IsNull() && !plan.Env.IsUnknown() {
		envMap := make(map[string]types.String)
		plan.Env.ElementsAs(context.Background(), &envMap, false)
		for k, v := range envMap {
			sb.WriteString(" --env " + client.ShellQuote(k+"="+v.ValueString()))
		}
	}

	// Integrations.
	if !plan.Integrations.IsNull() && !plan.Integrations.IsUnknown() {
		integrations := make([]types.String, 0, len(plan.Integrations.Elements()))
		plan.Integrations.ElementsAs(context.Background(), &integrations, false)
		for _, i := range integrations {
			sb.WriteString(" --integration=" + client.ShellQuote(i.ValueString()))
		}
	}

	return sb.String(), nil
}

// applyVMResponse copies API response fields into the model, leaving
// user-managed fields (image, disk, env, etc.) unchanged.
func applyVMResponse(m *vmResourceModel, vm vmAPIResponse) {
	name := vm.effectiveName()
	m.ID = types.StringValue(name)
	m.Name = types.StringValue(name)
	m.Hostname = types.StringValue(vm.effectiveHostname())
	if vm.Status != "" {
		m.Status = types.StringValue(vm.Status)
	} else if m.Status.IsNull() || m.Status.IsUnknown() {
		m.Status = types.StringValue("")
	}
	if vm.Region != "" {
		m.Region = types.StringValue(vm.Region)
	} else if m.Region.IsNull() || m.Region.IsUnknown() {
		m.Region = types.StringValue("")
	}

	// Only overwrite image from the API if non-empty.
	if vm.Image != "" {
		m.Image = types.StringValue(vm.Image)
	}
	// Disk: convert bytes to a GB string if we have it, otherwise keep user value.
	if vm.DiskCapacityBytes > 0 {
		gb := vm.DiskCapacityBytes / 1073741824
		m.Disk = types.StringValue(fmt.Sprintf("%dGB", gb))
	}

	// Ensure computed collections are set to non-null if not already configured.
	if m.Env.IsNull() || m.Env.IsUnknown() {
		m.Env = types.MapValueMust(types.StringType, map[string]attr.Value{})
	}
	if m.Integrations.IsNull() || m.Integrations.IsUnknown() {
		m.Integrations = types.ListValueMust(types.StringType, []attr.Value{})
	}
}

// trimBOM removes any UTF-8 BOM from the start of b.
func trimBOM(b []byte) []byte {
	if len(b) >= 3 && b[0] == 0xEF && b[1] == 0xBB && b[2] == 0xBF {
		return b[3:]
	}
	return b
}
